[package]
name = "kollider-hedge-domain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.19", features = [ "serde" ] }
kollider-client = { git = "https://github.com/standardsats/kollider-client", rev = "fb90c3d51aad8a4b93379b482fecd41e20a27a95", features = [ "ws", "openapi" ] }
reqwest = { version = "0.11", features = [ "json" ] }
rweb = { version = "0.15.0", features = ["openapi", "chrono"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
